# Generated by Django 5.0.2 on 2024-03-07 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_date_ordered_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 47, 47, 573930)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 23, 47, 47, 572937)),
        ),
    ]
